### ISSUE TITLE
Documentation CHMs are no longer updated

### ISSUE THREAD

**Issue by cmb69** [php/systems#58]
We offer downloads of the documentation (https://www.php.net/download-docs.php), but apparently the CHM and enhanced CHM are no longer up to date (26 July). I have no idea what would need to be done to fix that, though.

**Comment by jimwins** [comment]
I don't have access to rsync.php.net, but it looks like part of the problem may be the SSL certificate on the external server where these are built. I can load https://www.mumumu.org/chm/build.log in a browser or using curl on macOS, but curl on Ubuntu 24.04 complains about the certificate, and so does the `scripts/fetch-chms.php` script in `doc-base`, which looks like what is run to pull these files. There's probably some way to turn off the certificate validation in the stream wrapper (or should be?) but I'm not sure what it is.

**Comment by jimwins** [comment]
These are updated now.
