### ISSUE TITLE
issues: doc.php.net do not have a secure HTTPS connection.

### ISSUE THREAD

**Issue by iamprogrammerlk** [php/systems#61]
It seems like doc.php.net does not have HTTPS protocol support configured. nowadays HTTPS is considered required for even simple static websites. the Chrome browser is warning me when I am trying to access this site. Please configure the SSL certificate for doc.php.net.

**Comment by php-pulls** [comment]
We're currently migrating this service, so this will happen soon enough.

**Comment by derickr** [comment]
We're migrating this service, so this will happen soon enough.

**Comment by jimwins** [comment]
Fixed, finally!
